[project]
name = "ngp-information-portal"
version = "0.1.0"
description = "A very informational portal"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mkdocs-git-revision-date-localized-plugin>=1.5.0",
    "mkdocs-material>=9.7.0",
]

